### ISSUE TITLE
Types in Calculator model.

### ISSUE THREAD

**Issue by gwhilts** [richardtemple/retirement_calculator#17]
Looking through the code in the model, I see that you're repeatedly casting to the appropriate type (and even converting values) to do calculations. For example, whenever you want the interest rate you use:

```
@inflation_rate.to_f / 100
```

The reason for this seems to be that you're storing all the values as Strings. If it were my choice, I would make sure all the model's values were already the right type and value, then worry about stringifying them in the view if needed. For interest if you stored the interest rate as 0.05 in the model, you could eliminate all that `.to_f / 100` stuff you've got over and over. Casting to String for the view is mostly automagical. There's even a built-in view helper to show the value as percentage.

**Comment by richardtemple** [comment]
The auto convert would be nice.  I was getting a bunch of errors when I didn't use the to_f, etc.  I must have been doing something wrong.  The other issue is, getting the model to have the right type automatically.  It was easy with the migration, but I didn't know how to do it without full ActiveRecord.  I'll research.

**Comment by richardtemple** [comment]
When I take them out….

**Comment by richardtemple** [comment]
Shoot, replying with screenshot isn't good.  :)

**Comment by gwhilts** [comment]
Web forms return all the params as strings. When we had an ActiveRecord model, the model could infer the correct types to store from the db schema and would handle the casting before storing them. Without a db schema, we'll have to do the conversions ourselves before assigning them to the model.  This mean that we'll have to overwrite the default accessors methods, but it's still probably better to do this once in the setter methods than do it over and over again each time we want to use the data.

**Comment by richardtemple** [comment]
Sounds good.  :)

**Comment by richardtemple** [comment]
Went back to attr_accessor for model.  It seems cleaner to me.  Would love ActiveModel to have some type settings without DB!
